version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=http://localhost
    restart: unless-stopped
  client:
    build: ./client
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped 